export const pets = {
  1: {
    id: 1,
    type: 'Dog',
    name: 'Max',
    breed: 'Labrador',
    color: 'Golden',
    mood: 'Happy',
    energy: 100,
  },
  2: {
    id: 2,
    type: 'Cat',
    name: 'Bella',
    breed: 'Siamese',
    color: 'Cream',
    mood: 'Excited',
    energy: 95,
  },
  3: {
    id: 3,
    type: 'Bird',
    name: 'Charlie',
    breed: 'Parakeet',
    color: 'Green',
    mood: 'Relaxed',
    energy: 85,
  },
  4: {
    id: 4,
    type: 'Fish',
    name: 'Nemo',
    breed: 'Clownfish',
    color: 'Orange',
    mood: 'Playful',
    energy: 90,
  },
  5: {
    id: 5,
    type: 'Dog',
    name: 'Buddy',
    breed: 'Golden Retriever',
    color: 'Golden',
    mood: 'Hungry',
    energy: 80,
  },
  6: {
    id: 6,
    type: 'Cat',
    name: 'Daisy',
    breed: 'Persian',
    color: 'White',
    mood: 'Calm',
    energy: 75,
  },
  7: {
    id: 7,
    type: 'Bird',
    name: 'Rocky',
    breed: 'Cockatiel',
    color: 'Gray',
    mood: 'Sleepy',
    energy: 70,
  },
  8: {
    id: 8,
    type: 'Fish',
    name: 'Goldie',
    breed: 'Goldfish',
    color: 'Gold',
    mood: 'Energetic',
    energy: 85,
  },
  9: {
    id: 9,
    type: 'Dog',
    name: 'Bailey',
    breed: 'Siberian Husky',
    color: 'Gray',
    mood: 'Anxious',
    energy: 90,
  },
  10: {
    id: 10,
    type: 'Cat',
    name: 'Sadie',
    breed: 'Maine Coon',
    color: 'Gray and White',
    mood: 'Nervous',
    energy: 95,
  },
};
